image: gitpod/workspace-full
tasks:
  - name: Define Java and Mven
    before: |
      sdkman_auto_answer=true sdk install java 11.0.20.1-zulu -y
      sdkman_auto_answer=true sdk install maven 3.9.4 -y
      java -version
      mvn --version
    command: |
      mvn package
  
vscode:
  extensions:
    - vscjava.vscode-java-pack
