image: gitpod/workspace-full
tasks:
  - name: Define Java and Mven
    before: |
      sdk install java 11.0.20.1-zulu -y
      sdk install maven 3.9.4 -y
      java -version
      mvn --version
    command: |
      mvn dependency:resolve
  
vscode:
  extensions:
    - vscjava.vscode-java-pack
